### PR TITLE
Refactors and Comments

### PR DESCRIPTION
**Pull request by AEFeinstein**
Shouldn't have any functional changes

### CODE REVIEW

**Comment by cnlohr** [comment]
Aah just saw your note in #77 ... I will look into this soon.

**Comment by cnlohr** [comment]
@AEFeinstein  Can you pull and refresh?  Or should this be closed?

**Comment by AEFeinstein** [comment]
Created https://github.com/AEFeinstein/colorchord/pull/2, will manually merge in the near future.

**Comment by AEFeinstein** [comment]
@cnlohr, do you _really_ need image.elf-0x00000.bin checked in?

**Comment by AEFeinstein** [comment]
Pulled and refreshed

**Comment by cnlohr** [comment]
@AEFeinstein Can you test colorchord desktop edition based on your changes here?

**Comment by bbkiwi** [comment]
I've just compared @cnlohr master on a nodemcu with @AEFeinstein  PR. Both seem to work with no major problems.  Compatible with my recent changes. Runs at 400Hz and with SORT=1 at 250Hz. I like @AEFeinstein handling of the configuration parameters. I get no warnings compiling @cnlohr, but get these after the PR

`~/82XX-projects/colorchord/embedded8266 (testAEF) $ make all
/home/bill/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -mlongcalls -Os -I/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/include -Iesp82xx/include -I. -Iesp82xx/fwsrc -Iuser -I../embeddedcommon -DUSE_OPTIMIZE_PRINTF -DMFS_PAGE_OFFSET=532480  -DICACHE_FLASH -DDISABLE_CHARRX  -DWS2812_FOUR_SAMPLE     -DSOFTAP_CHANNEL=6 -DWEB_PORT=80 -DCOM_PORT=7777 -DBACKEND_PORT=7878  -DSLOWTICK_MS=50 -DVERSSTR='"Version: 8d82a-dev - Build Fri, May 24 2019, 17:34:29 +1200 with -DUSE_OPTIMIZE_PRINTF -DMFS_PAGE_OFFSET=532480  -DICACHE_FLASH -DDISABLE_CHARRX  -DWS2812_FOUR_SAMPLE     -DSOFTAP_CHANNEL=6 -DWEB_PORT=80 -DCOM_PORT=7777 -DBACKEND_PORT=7878  -DSLOWTICK_MS=50"' -g esp82xx/fwsrc/uart.c esp82xx/fwsrc/esp82xxutil.c esp82xx/fwsrc/flash_rewriter.c esp82xx/fwsrc/http.c esp82xx/fwsrc/commonservices.c esp82xx/fwsrc/http_custom.c esp82xx/fwsrc/mdns.c esp82xx/fwsrc/mfs.c user/custom_commands.c user/user_main.c user/ws2812_i2s.c user/hpatimer.c user/adc.c ../embeddedcommon/DFT32.c ../embeddedcommon/embeddednf.c ../embeddedcommon/embeddedout.c -flto -Wl,--relax -Wl,--gc-sections -nostdlib -L/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib -Lesp82xx/libgcc_stripped.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libmain.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/liblwip.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libssl.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libupgrade.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libnet80211.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libwpa.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libphy.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/liblwip.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libcrypto.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libc.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libespnow.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libpp.a esp82xx/libgcc_stripped.a -T /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/ld/eagle.app.v6.ld -T /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/ld/eagle.rom.addr.v6.ld -Wl,-Map,output.map -B/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib  -o image.elf
user/user_main.c: In function 'user_init':
user/user_main.c:270:2: warning: passing argument 1 of 'ets_timer_disarm' discards 'volatile' qualifier from pointer target type [enabled by default]
  os_timer_disarm(&some_timer);
  ^
In file included from user/user_main.c:13:0:
/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/include/osapi.h:66:6: note: expected 'struct ETSTimer *' but argument is of type 'volatile struct ETSTimer *'
 void ets_timer_disarm(os_timer_t *ptimer);
      ^
user/user_main.c:271:2: warning: passing argument 1 of 'ets_timer_setfn' discards 'volatile' qualifier from pointer target type [enabled by default]
  os_timer_setfn(&some_timer, (os_timer_func_t *)myTimer, NULL);
  ^
In file included from user/user_main.c:13:0:
/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/include/osapi.h:67:6: note: expected 'struct ETSTimer *' but argument is of type 'volatile struct ETSTimer *'
 void ets_timer_setfn(os_timer_t *ptimer, os_timer_func_t *pfunction, void *parg);
      ^
user/user_main.c:272:2: warning: passing argument 1 of 'ets_timer_arm_new' discards 'volatile' qualifier from pointer target type [enabled by default]
  os_timer_arm(&some_timer, 100, 1);
  ^
In file included from user/user_main.c:13:0:
/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/include/osapi.h:65:6: note: expected 'struct ETSTimer *' but argument is of type 'volatile struct ETSTimer *'
 void ets_timer_arm_new(os_timer_t *ptimer, uint32_t time, bool repeat_flag, bool ms_flag);
      ^
PATH=/home/bill/esp-open-sdk/xtensa-lx106-elf/bin:/home/bill/bin:/home/bill/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/bill/esp-open-sdk/xtensa-lx106-elf/bin /home/bill/esp-open-sdk/esptool/esptool.py elf2image image.elf
esptool.py v1.2
`

> ~/82XX-projects/colorchord/embedded8266 (testAEF) $ make all
/home/bill/esp-open-sdk/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -mlongcalls -Os -I/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/include -Iesp82xx/include -I. -Iesp82xx/fwsrc -Iuser -I../embeddedcommon -DUSE_OPTIMIZE_PRINTF -DMFS_PAGE_OFFSET=532480  -DICACHE_FLASH -DDISABLE_CHARRX  -DWS2812_FOUR_SAMPLE     -DSOFTAP_CHANNEL=6 -DWEB_PORT=80 -DCOM_PORT=7777 -DBACKEND_PORT=7878  -DSLOWTICK_MS=50 -DVERSSTR='"Version: 8d82a-dev - Build Fri, May 24 2019, 17:34:29 +1200 with -DUSE_OPTIMIZE_PRINTF -DMFS_PAGE_OFFSET=532480  -DICACHE_FLASH -DDISABLE_CHARRX  -DWS2812_FOUR_SAMPLE     -DSOFTAP_CHANNEL=6 -DWEB_PORT=80 -DCOM_PORT=7777 -DBACKEND_PORT=7878  -DSLOWTICK_MS=50"' -g esp82xx/fwsrc/uart.c esp82xx/fwsrc/esp82xxutil.c esp82xx/fwsrc/flash_rewriter.c esp82xx/fwsrc/http.c esp82xx/fwsrc/commonservices.c esp82xx/fwsrc/http_custom.c esp82xx/fwsrc/mdns.c esp82xx/fwsrc/mfs.c user/custom_commands.c user/user_main.c user/ws2812_i2s.c user/hpatimer.c user/adc.c ../embeddedcommon/DFT32.c ../embeddedcommon/embeddednf.c ../embeddedcommon/embeddedout.c -flto -Wl,--relax -Wl,--gc-sections -nostdlib -L/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib -Lesp82xx/libgcc_stripped.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libmain.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/liblwip.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libssl.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libupgrade.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libnet80211.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libwpa.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libphy.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/liblwip.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libcrypto.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libc.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libespnow.a /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib/libpp.a esp82xx/libgcc_stripped.a -T /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/ld/eagle.app.v6.ld -T /home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/ld/eagle.rom.addr.v6.ld -Wl,-Map,output.map -B/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/lib  -o image.elf
user/user_main.c: In function 'user_init':
user/user_main.c:270:2: warning: passing argument 1 of 'ets_timer_disarm' discards 'volatile' qualifier from pointer target type [enabled by default]
  os_timer_disarm(&some_timer);
  ^
In file included from user/user_main.c:13:0:
/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/include/osapi.h:66:6: note: expected 'struct ETSTimer *' but argument is of type 'volatile struct ETSTimer *'
 void ets_timer_disarm(os_timer_t *ptimer);
      ^
user/user_main.c:271:2: warning: passing argument 1 of 'ets_timer_setfn' discards 'volatile' qualifier from pointer target type [enabled by default]
  os_timer_setfn(&some_timer, (os_timer_func_t *)myTimer, NULL);
  ^
In file included from user/user_main.c:13:0:
/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/include/osapi.h:67:6: note: expected 'struct ETSTimer *' but argument is of type 'volatile struct ETSTimer *'
 void ets_timer_setfn(os_timer_t *ptimer, os_timer_func_t *pfunction, void *parg);
      ^
user/user_main.c:272:2: warning: passing argument 1 of 'ets_timer_arm_new' discards 'volatile' qualifier from pointer target type [enabled by default]
  os_timer_arm(&some_timer, 100, 1);
  ^
In file included from user/user_main.c:13:0:
/home/bill/82XX-projects/colorchord/embedded8266/esp82xx/toolchain/esp_nonos_sdk/include/osapi.h:65:6: note: expected 'struct ETSTimer *' but argument is of type 'volatile struct ETSTimer *'
 void ets_timer_arm_new(os_timer_t *ptimer, uint32_t time, bool repeat_flag, bool ms_flag);
      ^
PATH=/home/bill/esp-open-sdk/xtensa-lx106-elf/bin:/home/bill/bin:/home/bill/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/bill/esp-open-sdk/xtensa-lx106-elf/bin /home/bill/esp-open-sdk/esptool/esptool.py elf2image image.elf
esptool.py v1.2

**Comment by AEFeinstein** [comment]
I made some variables volatile because they were used inside and outside interrupts, but I guess the compiler isn't thrilled with that. I should be able to clean up those warnings with some casting later today.

**Comment by AEFeinstein** [comment]
Fixed the volatility thing. I'm getting this warning too:
```
user/ws2812_i2s.c:466:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  ~0b1000100010001000, ~0b1000100010001100, ~0b1000100011001000, ~0b1000100011001100,
  ^
user/ws2812_i2s.c:466:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:466:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:466:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:467:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  ~0b1000110010001000, ~0b1000110010001100, ~0b1000110011001000, ~0b1000110011001100,
  ^
user/ws2812_i2s.c:467:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:467:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:467:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:468:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  ~0b1100100010001000, ~0b1100100010001100, ~0b1100100011001000, ~0b1100100011001100,
  ^
user/ws2812_i2s.c:468:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:468:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:468:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:469:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
  ~0b1100110010001000, ~0b1100110010001100, ~0b1100111011001000, ~0b1100110011001100,
  ^
user/ws2812_i2s.c:469:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:469:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
user/ws2812_i2s.c:469:2: warning: large integer implicitly truncated to unsigned type [-Woverflow]
```

The code it's whining about seems perfectly reasonable though. 16 binary digits in a uint16_t looks good to me

```
static const uint16_t bitpatterns[16] = {
	~0b1000100010001000, ~0b1000100010001100, ~0b1000100011001000, ~0b1000100011001100,
	~0b1000110010001000, ~0b1000110010001100, ~0b1000110011001000, ~0b1000110011001100,
	~0b1100100010001000, ~0b1100100010001100, ~0b1100100011001000, ~0b1100100011001100,
	~0b1100110010001000, ~0b1100110010001100, ~0b1100111011001000, ~0b1100110011001100,
};
```

**Comment by bbkiwi** [comment]
I had noticed this warning when trying @cnlohr  master which has #define LUXETRON  at line 55 in ws2812_i2s.c which then defines INVERT. You won't get this if comment out the #define LUXETRON (which I did in my tests, (it should be in ccconfig.h or user.cfg). Maybe the compiler views 0b1000100010001000 as negative, so warns when bitwise invert it???  Explictly writing the inversioned values should get rid of the warning. 

`static const uint16_t bitpatterns[16] = {
	0b0111011101110111, ... `

**Comment by AEFeinstein** [comment]
Or maybe appending a u? Just brainstorming while out on the town.

**Comment by bbkiwi** [comment]
Appending u didn't work. 
This get rid of the warnings
`static const uint16_t bitpatterns[16] = {
	0b0111011101110111, 0b0111011101110011, 0b0111011100110111, 0b0111011100110011,
	0b0111001101110111, 0b0111001101110011, 0b0111001100110111, 0b0111001100110011,
	0b0011011101110111, 0b0011011101110011, 0b0011011100110111, 0b0011011100110011,
	0b0011001101110111, 0b0011001101110011, 0b0011000100110111, 0b0011001100110011,
};`

I forgot to include ccconfig.h in my last PR. So I done that and made the above fix in a new PR.

**Comment by AEFeinstein** [comment]
Sounds good. Any other changes anyone wants me to make here?

**Comment by bbkiwi** [comment]
PR #91 will make the changes, or you can fix it in your's and Charles can ignore mine.

**Comment by AEFeinstein** [comment]
#91 is already up, so lets just use that

**Comment by cnlohr** [comment]
Closing PR based on comments.

**Pull request closed without merging**
