### PR TITLE
Fetch submodule automatically and bump to latest version

### PR DESCRIPTION
**Pull request by con-f-use**

### CODE REVIEW

**Comment by cnlohr** [comment]
OH NO! I did this before reading this - sort of - I did it without it being automatic.  I think it's better to leave as utility, rather than checking all possible build choices.

**Comment by cnlohr** [comment]
Sorry, same thing as the other tree - I added an option to do this manually, it seems a bit onerous to check against any build condition and do it automatically.

**Comment by con-f-use** [comment]
> Well that would only update and already puled submodule. Since it's in the submodule, we can't use it in the top level-project, when the user forgot to git clone --recursive. Should be in both, the Makefile.example of the submodule and the Makefile of the top-level.
see https://github.com/cnlohr/esp82xx/issues/9#issuecomment-241036992

**Comment by cnlohr** [comment]
See #9 in esp82xx - I am just really trying to avoid calling out targets.

**Comment by cnlohr** [comment]
Can't tell... should this be closed?

**Pull request closed without merging**
