### PR TITLE
Add VERIFY_FLASH_WRITE as remedy for #15

### PR DESCRIPTION
**Pull request by con-f-use**
- Small fix in Makefile and binaries regarding name of firmware files
- Add `netweb` rule in main Makefile to transfer the page directly
- Add an option `VERIFY_FLASH_WRITE` to help with #15 (writing to flash fails sometimes on ESP-01 modules). If enabled in `makeconf.inc`, the ESP reads the flash memory after writing and verifies that its data and that of the buffer match. It is disabled by default.

### CODE REVIEW

**Comment by cnlohr** [comment]
How does -DVERIFY_FLASH_WRITE work?  Also, Any ideas on keeping this, and the other two projects in sync?

**Comment by con-f-use** [comment]
It's rather simple really. The ESP runs this code, right after writing to flash:
```
uint8_t  __attribute__ ((aligned (32))) buf[128];
for(jj=0; jj<datlen; jj+=128) {
    spi_flash_read( nr+jj, (uint32*)buf, 128 );
    if( ets_memcmp( buf, buffer+jj, jj+128>datlen ? datlen%128 : 128 ) != 0 ) goto failw;
}
```
This creates another buffer. Freshly written flash portions are read into this buffer in chunks and than compared against what the esp received as data. If they don't match up, i.e. the flash write was faulty, the firmware sends "!FW\r\n" as answer. I opted for chunks rather than the whole block, because I didn't want to allocate another buffer of 1300 bytes.

As noted in #15 I noticed that the code above sometimes causes a reset in my EPS, when running colorchord, but not with the other projects (e.g. eps8266ws2812). I can't really explain why, maybe the code takes to long and I need to reset the watchdog.

@project-syncing: The easiest way to keep them in sync would be to create a repository for the common files and then include that as a submodule in all the derivative ESP projects. As bonus it would be really easy to start a new esp-based project. It think this is the most elegant. Another possiblity is to combine everything into one project and enable "features" via a compile flag, just like verifying the flash write is enabled with "-DVERIFY_FLASH_WRITE" in this pull request. But I think that would be somewhat messy and confusing.

**Comment by cnlohr** [comment]
I don't know what's going on with that reset :(.  I used to have mystery resets on some projects and never found out what was going on.

I've never found out how to use external repositories in my git trees.  I try to make things reasonable.  I tried to keep the web-utils "menuinterface.js" file and "commonfiles" folder as uniform as I could, but they did diverge.  Would the idea be to make a repo like "cn8266" where it has the utils in the web folder, meuinterface, and commonfiles in it?  Would it have an example project in it?  Should we use an include for the Makefile?

I really don't want to put everything in one project.  It would make it difficult to make brand new projects. 

For your demo submodule project, what would I search to learn how to do that?  Are the pointers like "Makefile" treated as symlinks or does Git just know how to maintain them?

**Comment by con-f-use** [comment]
I'm no expert, but my example above works well and I adapted it for [colorchord](https://github.com/con-f-use/colorchord) and ws2812i2c.

> I've never found out how to use external repositories in my git trees.
With submodules it's fairly simple. You create the specific project first, e.g. colorchord. Then you do a `submodule add git@url.to.common.repository.git`. That causes the common repository to be included into the top-level project as its own folder. This folder is frozen in time. If you make commits to the common files, nothing changes in your top-level project. Only after a `git submodule update` and subsequent `git commit` in the top level does it's common folder get bumped to the next version. That ensures stability and trackability of changes. If you clone a top-level project, you need to clone it with the submodule, i.e. use git's `--recursive` option as in `git clone --recursive url.to.top-level.repo.git`

> Would the idea be to make a repo like "cn8266" where it has the utils in the web folder, meuinterface, and commonfiles in it?
Yes.

> Would it have an example project in it?
Sort of.  It would have example files that just need to be linked into the top-level to make a basic project.

> Should we use an include for the Makefile?
> I really don't want to put everything in one project. It would make it difficult to make brand new projects. 
If you make a basic project, you just soft-link the example files into your top-level. If you require more changes, you use make's include directive to include a common makefile and tweak make variables/add rules after the include. If you need even more custom stuff, you write your own files from scratch and ignore most of the common ones. It's really a modular approach. I don't think it would make new projects more difficult (except for the first project, where you still have to get used to stuff).

Maybe looking at both my [basic](https://github.com/con-f-use/esp82XX-basic) and [colorcord](https://github.com/con-f-use/colorchord) example helps. In the basic example almost everything is linked from the [common repository](https://github.com/con-f-use/esp82XX). In the colorchord example not so much is linked but rather copied and edited. For example, look at the Makefile:
```
include esp82XX/common.mf
include esp82XX/main.mf

SRCS += user/ws2812_i2s.c \
	user/hpatimer.c \
	user/adc.c \
	../embeddedcommon/DFT32.c \
	../embeddedcommon/embeddednf.c \
	../embeddedcommon/embeddedout.c

LDFLAGS_CORE += -Wl,-Map,output.map
```
I include two Makefiles from the common repository (which is called "esp82XX") and then just add additional files to the SRCS and a small tweak for the `LDFLAGS`. In the basic project, this would just be a soft-link to the example Makefile `esp82XX/Makefile.example`.

**Comment by cnlohr** [comment]
I really like this.  Is there much risk in pushing this back to the main repo?  Is it ready for that yet?

Re: Makefile/etc.  I do think the includes are the way to go.

I really like this!  I had no idea there was any such facility.  With SVN, externals are pretty awful.

I am still working a great deal on the espusb stuff, but even that I want to get converted over, too now!

**Comment by con-f-use** [comment]
Glad you like it. There are a few steps I'd recommend you to do before pulling it to the main repo:

 1. Create an empty repo called `esp82XX` or whatever you want the common stuff to be called
 2. Let me fork it, fill the fork with the common files and make a pull request
 3. Let me "submodule" your common repo into my fork of colorchord and make a pull request
 4. ...
 5. Profit (also accept the pull request)

That way all the repos remain in your hand entirely.

**Comment by cnlohr** [comment]
I was going to hope to remain in control of the master copy of that repo, but it's more of personal preference.  I can probably get all of this set up tonight.

I haven't taken taken a look at your issue_command... is it as fast/memory light? I can believe there would be better ways to do it than I am!

P.S. I have given a lot of thought to something that can splay apart tab-deliminated strings.  I think that would be a good move, or maybe a "capture and next" that I did on some of my projects (not all).  :( That was waaay too much diversity between projects.  I am so excited to get things unified.  It will also incentivize me to clean up commonservices.

**Comment by con-f-use** [comment]
You *will* remain in control of the *all* the repos and their files. That's why I suggest step 1 from above. For now, we just need you to create an empty repository for the common files.

**Comment by cnlohr** [comment]
https://github.com/cnlohr/esp82xx

**Comment by con-f-use** [comment]
Okay sorry, I didn't know forking an empty repositories is impossible. Could you add a token (non-empty) file insed esp82xx?

**Comment by cnlohr** [comment]
Added a file!  I will try to elaborate more during my lunch break today.

**Comment by cnlohr** [comment]
I would rather have SRCS defined in the bas include file, and then use the SRC:=$(SRCS) usb.c mything.c, etc (or the += operator).  I don't really want to autodetect since that would make it more difficult to debug when things don't go right.  I think the user's project Makefile should be the one to get the ultimate decision on what srcs to include, cflags, everything else, and how it goes together.

Re: The "capture and next" is more for cleaning up the way I am doing string processing in the issue_command function.

Get that pull request moving and I'll try to get my espusb project integrated.

**Comment by con-f-use** [comment]
[Pull request](https://github.com/cnlohr/esp82xx/pull/1#issue-172002388) is made. I will update my colorchord fork, as soon as you approve the request. Then I'll make a request to pull colorchord. Fun!

**Comment by cnlohr** [comment]
done

**Pull request merged**
